server:
  port: 8086
  error:
    include-message: always

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  application: 
    name: sbms-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Database Configuration
  datasource:
    url:  jdbc:postgresql://smart-board-db.c7miuo2k4f6h.ap-south-1.rds.amazonaws.com:5432/sbms_monolith
    username: monolith_user
    password: "monolith09090909"
    driver-class-name: org.postgresql.Driver
    hikari:     
      maximum-pool-size: 5
      minimum-idle: 1        # Only keep 1 connection open when idle
      idle-timeout: 30000    # Release idle connections after 30 seconds
      max-lifetime: 600000   # 10 minutes
      connection-timeout: 20000

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Mail / SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: thareesha01@gmail.com
    # Note: This is an App Password (not the actual Gmail password)
    password: foewigznsutmonhm 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Multipart File Upload Settings
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


aws:
  # WARNING: Hardcoding credentials is a security risk. Use environment variables or AWS IAM roles instead.
  accessKeyId: AKIA2AUOOUX3O5UUUYBN      
  secretAccessKey: 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  
  region: ap-south-1
  s3:
    bucketName: smart-board-project


sbms:
  admin:
    seed:
      enabled: true
    email: admin@smartboard.com
    password: Admin@123
    full-name: System Admin
  rabbitmq:
    enabled: false
    exchange: emergency

#url: jdbc:postgresql://smart-board-db.c7miuo2k4f6h.ap-south-1.rds.amazonaws.com:5432/smart-board